# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-07 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市名字')),
                ('desc', models.CharField(max_length=50, verbose_name='城市介绍')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='城市添加时间')),
            ],
            options={
                'verbose_name': '城市信息',
                'verbose_name_plural': '城市信息',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机构名字')),
                ('desc', models.TextField(max_length=500, verbose_name='机构介绍')),
                ('category', models.CharField(choices=[('pxjg', '培训机构'), ('gr', '个人'), ('gx', '高校')], default='pxjg', max_length=20, verbose_name='所属类别')),
                ('students', models.IntegerField(default=0, verbose_name='学生数')),
                ('cources_num', models.IntegerField(default=0, verbose_name='课程数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='机构点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='机构被收藏次数')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='logo')),
                ('addrsee', models.CharField(max_length=200, verbose_name='机构所在地址')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='机构添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '机构信息',
                'verbose_name_plural': '机构信息',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教师名字')),
                ('work_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('work_company', models.CharField(max_length=50, verbose_name='工作公司')),
                ('work_position', models.CharField(max_length=50, verbose_name='工作职位')),
                ('points', models.CharField(max_length=50, verbose_name='教学特点')),
                ('click_nums', models.IntegerField(default=0, verbose_name='教师点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='教师收藏次数')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='教师时间')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
    ]
