# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-10 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191210_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='学习时间(分钟算)'),
        ),
    ]
