# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/1.png', upload_to='media/%Y/%m'),
        ),
    ]
